global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL Master Exporter
  - job_name: 'postgres-master'
    static_configs:
      - targets: ['postgres-exporter-master:9187']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-master'
      - source_labels: []
        target_label: role
        replacement: 'master'

  # PostgreSQL Replica 1 Exporter  
  - job_name: 'postgres-replica1'
    static_configs:
      - targets: ['postgres-exporter-replica1:9187']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-replica1'
      - source_labels: []
        target_label: role
        replacement: 'replica'

  # PostgreSQL Replica 2 Exporter
  - job_name: 'postgres-replica2'
    static_configs:
      - targets: ['postgres-exporter-replica2:9187']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-replica2'
      - source_labels: []
        target_label: role
        replacement: 'replica'

  # PostgreSQL Replica 3 Exporter
  - job_name: 'postgres-replica3'
    static_configs:
      - targets: ['postgres-exporter-replica3:9187']
    scrape_interval: 5s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-replica3'
      - source_labels: []
        target_label: role
        replacement: 'replica'

  # HAProxy Stats
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8080']
    metrics_path: /stats/prometheus
    scrape_interval: 5s 